"""
This is a setup.py script generated by py2app

Usage:
    python setup.py py2app
"""
import os
import sys
import glob
import subprocess
from setuptools import setup


def get_command_out(command):
	try:
		return subprocess.check_output(command.split(' '))[:-1]
	except:
		return ''

def generate_build_info():
	""" Returns Builder information."""
	data = dict(
		user = get_command_out('whoami'),
		host = get_command_out('hostname'),
		revision = get_rev()
		)
	build_info = '\n'.join(['%s = "%s"' % (k,v) for k,v in data.iteritems()])
	print build_info
	f = open('src/buildinfo.py','w')
	f.write(build_info)

def delete_build_info():
	os.remove('src/buildinfo.py')

def get_rev():
	""" Returns Mercurial CVS rev."""
	import commands
	import re
	out = get_command_out('hg summary')
	match = re.search('parent:\s+([^\s]+)',out)
	if match:
		return match.groups()[0]
	else:
		return ''

def get_options():
	""" Returns Mac app options."""
	returns = {}
	from plistlib import Plist
	PLIST = Plist.fromFile('osx/Info.plist')
	PLIST.update ( dict(
			CFBundleShortVersionString = version.__version__+':'+get_rev(),
			NSHumanReadableCopyright = u"Copyright 2012 mei raka",
			))
	
	app_option = dict(
			plist=PLIST
			#iconfile='resources/osx/icon.icns'
			)
	returns['py2app'] = app_option
	
	return returns

import src.version as version


def get_pair(pair,base):
	lis = []
	for filename in os.listdir(base):
		if os.path.isdir(base+'/'+filename):
			get_pair(pair,base+'/'+filename)
		else:
			lis.append(base+'/'+filename)
	pair.append((base,lis))
	pair.reverse()
	return pair

generate_build_info()
resources_pair = []
locale_pair = []

setup_args = {}
setup_args['packages'] = ['MusicController']
setup_args['package_dir'] = {'MusicController':'src'}
setup_args['data_files'] = [('bin',['music-controller'])]
setup_args['setup_requires'] = ['python-mpd']

if sys.argv.count('py2app'):
	setup_args['app'] = ['src/__main__.py']
	setup_args['setup_requires'].append('py2app')
	setup_args['options'] = get_options()

if not sys.argv.count('test'):
	setup(name='MusicController',
		version=version.__version__,
		author='mei raka',
		**setup_args)
else:
	sys.path.append(os.path.abspath('src'))
	sys.path.append(os.path.abspath('tests'))
	import unittest
	import client_test
	classes = [getattr(client_test,i) for i in dir(client_test) if i.startswith('Test')]
	for i in classes:
		s = unittest.makeSuite(i)
		unittest.TextTestRunner(verbosity=2).run(s)

delete_build_info()
